---
# This play should occur before Postfix.
# TODO: handle multiple domains better
- name: install opendkim
  apt:
    name:
    - opendkim
    - opendkim-tools
    state: latest

- name: manage /etc/opendkim/keys
  file:
    path: /etc/opendkim/keys
    state: directory
    owner: root
    group: opendkim
    mode: 0750

- name: make opendkim key
  command: opendkim-genkey -s mail -d {{ mail_domain }}
  args:
    chdir: /etc/opendkim/keys
    creates: /etc/opendkim/keys/mail.private

- name: set dkim key permissions
  file:
    path: /etc/opendkim/keys
    state: directory
    owner: root
    group: opendkim
    mode: 0750
    recurse: yes

- name: modify /etc/default/opendkim
  lineinfile:
    path: /etc/default/opendkim
    regexp: '^SOCKET='
    line: 'SOCKET="inet:12301@127.0.0.1"'

- name: manage /etc/opendkim.conf
  template:
    src: opendkim.conf
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: 0755
  notify:
    - restart opendkim

